{"userprofile": {"name": "Birinder Singh",
  "current_title": "Data Scientist at Integra (AI/ML) Data and Analytic Solutions",
  "location": "Canada",
  "description": "I graduated from the Master of Data Science, University of British Columbia, Vancouver. During the final phaseof the program, I worked on a 2-month Capstone project where I along with two fellow students developed aworkflow to automate the mapping of landslide detection and delineation from LiDAR images usin...see more...see more",
  "interest": ["IIT Alumni in Canada",
   "Accenture",
   "Business Analyst/Data Scientist Jobs",
   "Advanced Analytics and Data Science",
   "LinkedIn",
   "Data Scientist Jobs"],
  "url":"Null"},
 "experience": [{"company": "Integra (AI/ML) Data and Analytic Solutions",
   "title": "Data Scientist",
   "dates_employed": "Jul 2019 – Present",
   "employment_duration": "10 mos",
   "job_detail": " Skillsets: 1. Multivariate Time Series Analysis 2. Web Scraping 3. Data cleaning, wrangling, statistical analysis and visualization 4. Anomaly Detection and Clustering 5. Apache Spark - Databricks 6. Proficient in various Open Source Tools required for Data preparation, preprocessing, wrangling/visualization up-to building and deploying ML models Certified in Dataiku level 1 "},
  {"company": "BGC Engineering Inc.",
   "title": "Data Scientist (UBC MDS Capstone Project)",
   "dates_employed": "Apr 2019 – Jun 2019",
   "employment_duration": "3 mos",
   "job_detail": " •\tDeveloped a workflow to automate the mapping of landslide detection and delineation from LiDAR images using deep learning techniques •\tEmployed efficient and scalable programming techniques to train deep learning models on a large image dataset •\tCombined deep learning and domain expertise within 10 weeks to deliver a workflow capable of significantly reducing manual intervention "},
  {"company": "Mathnasium Learning Centers",
   "title": "Instructor",
   "dates_employed": "May 2018 – Aug 2018",
   "employment_duration": "4 mos",
   "job_detail": " •  Taught the concepts of algebra, statistics and calculus to students up to grade 12"},
  {"company": "Schlumberger",
   "title": "Intern (Data Consulting Services)",
   "dates_employed": "Jun 2012 – Jul 2012",
   "employment_duration": "2 mos",
   "job_detail": " Carried out a Comparative Study of Water Saturation Calculation using Resistivity and Sigma Methods. Worked on Techlog wellbore software to carry on ELAN (Elemental Analysis) and saturation computations using different methods followed by detailed petrophysical interpretations. "},
  {"company": "Schlumberger",
   "title": ["Petro Technical Engineer (Data Consulting Services, Global Data Services HUB)",
    "PetroTechnical Engineer and Technical Sales Engineer (Data Consulting Services)"],
   "dates_employed":"Null",
   "employment_duration": "4 yrs 8 mos",
   "job_detail": " • Technical backbone of a 5-member data consulting team involved in processing and interpretation of data from 100+ wells/yr • Optimized the data processing workflows by writing python scripts leading up to 30% reduction in turnaround time and significant improvement in service quality • Conducted alpha test of a next-generation cloud-based workspace enabling users across the globe to carry out exploratory data analysis on centralized servers •\tPlayed a pivotal role in setting up the data processing and interpretation HUB for Schlumberger in India resulting in significant cost savings • Educated fellow engineers to identify opportunities, approach clients and execute projects independently "}],
 "education": ["The University of British Columbia",
  "Indian Institute of Technology, Roorkee",
  "Schlumberger Training Centers Abu Dhabi, Houston and Paris"],
 "skills": ["Oilfield",
  "Python (Programming Language)",
  "R",
  "Petroleum",
  "Directional Drilling",
  "Data Analysis",
  "Statistics",
  "Business Development",
  "Geology",
  "Geophysics",
  "Data Visualization",
  "Data Modeling",
  "Cloud Computing",
  "Business Analysis",
  "Big Data",
  "Machine Learning",
  "Statistical Data Analysis",
  "Microsoft Excel",
  "Matlab",
  "C++",
  "Databases",
  "GitHub",
  "Docker",
  "SQL",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Team Leadership",
  "Teamwork",
  "Petrel",
  "Petrophysics"]}