{"userprofile": {"name": "Siphu Langeni, MS",
  "current_title": "Data Scientist | Machine Learning | Deep Learning",
  "location": "Greater Toronto Area Metropolitan Area",
  "description": "I turn Insights into Impact using data mining, data analytics and predictive modeling....see more...see more",
  "interest": ["RBC",
   "Wayne State University",
   "Black Women In AI (Artificial Intelligence)",
   "Data Scientists",
   "Tata Consultancy Services",
   "African Data Engineering and Science Association South African Chapter (ADESA)"],
  "url": "NULL"},
 "experience": [{"company": "Train The Data",
   "title": "Data Scientist",
   "dates_employed": "Jun 2019 – Present",
   "employment_duration": "11 mos",
   "job_detail": "NULL"},
  {"company": "ASA Staffing",
   "title": "Certified Registered Nurse Anesthetist",
   "dates_employed": "Oct 2015 – Jun 2018",
   "employment_duration": "2 yrs 9 mos",
   "job_detail": "NULL"},
  {"company": "Detroit Medical Center",
   "title": ["Certified Regisrered Nurse Anesthetist", "Registered Nurse"],
   "dates_employed": "NULL",
   "employment_duration": "12 yrs 7 mos",
   "job_detail": "NULL"}],
 "education": ["University of Michigan-Flint",
  "Metro College of Technology",
  "Wayne State University"],
 "skills": ["Statistical Modeling",
  "Creative Problem Solving",
  "Business Insights",
  "Machine Learning",
  "Statistics",
  "Data Mining",
  "SAS Programming",
  "Medical Education",
  "Curriculum Development",
  "Artificial Intelligence (AI)",
  "Data Science",
  "Deep Learning",
  "Data Analysis",
  "Python (Programming Language)",
  "R",
  "SQL",
  "Keras",
  "TensorFlow",
  "Microsoft Office",
  "Electronic Medical Record (EMR)",
  "Tableau",
  "ggplot",
  "Microsoft Excel",
  "Microsoft PowerPoint",
  "Teamwork",
  "Leadership",
  "Presentation Skills",
  "Decision-Making",
  "Mentoring",
  "Innovative",
  "Visualization",
  "Data Analytics",
  "Scikit-Learn",
  "Cost-effective Solutions",
  "Mentoring New Hires",
  "Clinical Instructor",
  "Neural Networks"]}