# query syntax
  GET /linkedin/_search 
  {
    "_source": ["userprofile.name","userprofile.current_title"], 
    "query":{
      "match":{
        "userprofile.current_title": "data engineer"
      }
    }
  }

create index 'linkedin'
DELETE linkedin
PUT linkedin

POST linkedin/_doc
{"userprofile": {"name": "Birinder Singh",
  "current_title": "Data Scientist at Integra (AI/ML) Data and Analytic Solutions",
  "location": "Canada",
  "description": "I graduated from the Master of Data Science, University of British Columbia, Vancouver. During the final phaseof the program, I worked on a 2-month Capstone project where I along with two fellow students developed aworkflow to automate the mapping of landslide detection and delineation from LiDAR images usin...see more...see more",
  "url": "https://www.linkedin.com/in/birinder-singh/"},
 "experience": [{"company": "Integra (AI/ML) Data and Analytic Solutions",
   "title": "Data Scientist",
   "dates_employed": "Jul 2019 – Present",
   "employment_duration": "10 mos"},
  {"company": "BGC Engineering Inc.",
   "title": "Data Scientist (UBC MDS Capstone Project)",
   "dates_employed": "Apr 2019 – Jun 2019",
   "employment_duration": "3 mos"},
  {"company": "Mathnasium Learning Centers",
   "title": "Instructor",
   "dates_employed": "May 2018 – Aug 2018",
   "employment_duration": "4 mos"},
  {"company": "Schlumberger",
   "title": "Intern (Data Consulting Services)",
   "dates_employed": "Jun 2012 – Jul 2012",
   "employment_duration": "2 mos"},
  {"company": "Schlumberger",
   "title": ["Petro Technical Engineer (Data Consulting Services, Global Data Services HUB)",
    "PetroTechnical Engineer and Technical Sales Engineer (Data Consulting Services)"],
   "dates_employed": "NULL",
   "employment_duration": "4 yrs 8 mos"}],
 "education": ["The University of British Columbia",
  "Indian Institute of Technology, Roorkee",
  "Schlumberger Training Centers Abu Dhabi, Houston and Paris"]}

POST linkedin/_doc
  {"userprofile": {"name": "Fan Fan",
  "current_title": "Data Scientist",
  "location": "Canada",
  "description": "",
  "url": "https://www.linkedin.com/in/fan-fan-01026071/"},
 "experience": [{"company": "BCG GAMMA",
   "title": "Data Scientist",
   "dates_employed": "Jul 2019 – Present",
   "employment_duration": "10 mos"},
  {"company": "Ontario Institute for Cancer Research",
   "title": "Co-op student",
   "dates_employed": "May 2015 – Dec 2015",
   "employment_duration": "8 mos"},
  {"company": "RBC",
   "title": ["Senior Manager, Risk Modeling and Machine Learning",
    "Senior Analyst, Machine Learning"],
   "dates_employed": "NULL",
   "employment_duration": "3 yrs 2 mos"}],
 "education": ["University of Waterloo", "University of Waterloo"]}
 
 POST linkedin/_doc
{"userprofile": {"name": "Jiayu Zhang",
  "current_title": "Data Engineer at Indoc Research",
  "location": "Canada",
  "description": "• Big Data Foundation: Spark, EC2, EMR, AWS (Amazon Web Services), Databricks, Hive, Hadoop• Machine Learning tools: Scikit-Learn, Keras, Spark ML• Database: MySQL, SQL Server, DynamoDB, Salesforce...see more...see more",
  "url": "https://www.linkedin.com/in/jz020/"},
 "experience": [{"company": "Indoc Research",
   "title": "Data Engineer",
   "dates_employed": "Nov 2019 – Present",
   "employment_duration": "6 mos"},
  {"company": "Beam Data",
   "title": "Data Science Consultant",
   "dates_employed": "Nov 2018 – Nov 2019",
   "employment_duration": "1 yr 1 mo"},
  {"company": "Strategy Institute",
   "title": "Database Marketing Analyst",
   "dates_employed": "Oct 2017 – Oct 2018",
   "employment_duration": "1 yr 1 mo"}],
 "education": ["University of Toronto", "WeCloudData", "BrainStation"]}
 
 POST linkedin/_doc
{"userprofile": {"name": "Pravin Khatake",
  "current_title": "Data Engineer at Scotiabank",
  "location": "Toronto, Ontario, Canada",
  "description": "I have unique blend of skills with 6+ years of experience in IT and Banking industries. Proven data analyticsprofessional skilled in collecting, cleaning, aggregating, modelling and insight visualization using SQL, Pythonand...see more...see more",
  "url": "https://www.linkedin.com/in/pravin-khatake/"},
 "experience": [{"company": "Scotiabank",
   "title": "Data Engineer",
   "dates_employed": "Mar 2020 – Present",
   "employment_duration": "2 mos"},
  {"company": "RBL Bank",
   "title": "Commercial Analyst",
   "dates_employed": "Sep 2018 – Mar 2019",
   "employment_duration": "7 mos"},
  {"company": "YES BANK",
   "title": "Account Relationship Manager",
   "dates_employed": "Mar 2017 – Sep 2018",
   "employment_duration": "1 yr 7 mos"},
  {"company": "HDFC Bank",
   "title": "Account Relationship Manager",
   "dates_employed": "Apr 2015 – Mar 2017",
   "employment_duration": "2 yrs"},
  {"company": "Larsen & Toubro",
   "title": "Summer Intern",
   "dates_employed": "Apr 2014 – Jun 2014",
   "employment_duration": "3 mos"}],
 "education": ["Jamnalal Bajaj Institute of Management Studies",
  "Veermata Jijabai Technological Institute (VJTI)"]}
 
 POST linkedin/_doc
{"userprofile": {"name": "Gaganpreet Singh",
  "current_title": "Data Engineer at ResMed",
  "location": "Canada",
  "description": "An analytical and process-driven analyst with more than 2 years of experience in the procurement domain.Looking for full-time roles in Data Science involving Machine Learning, Artificial Intelligence and datavisualization....see more...see more",
  "url": "https://www.linkedin.com/in/gagan02singh/"},
 "experience": [{"company": "ResMed",
   "title": "Data Engineer",
   "dates_employed": "Dec 2019 – Present",
   "employment_duration": "5 mos"},
  {"company": "Saint Mary's University",
   "title": "Machine Learning Research Intern",
   "dates_employed": "May 2019 – Sep 2019",
   "employment_duration": "5 mos"},
  {"company": "Infosys",
   "title": "System Engineer trainee",
   "dates_employed": "Sep 2015 – Feb 2016",
   "employment_duration": "6 mos"},
  {"company": "RailTel Corporation of India Ltd",
   "title": "Internship",
   "dates_employed": "Jun 2014 – Jul 2014",
   "employment_duration": "2 mos"},
  {"company": "Infosys",
   "title": ["Associate Business Analyst", "System Engineer"],
   "dates_employed": "NULL",
   "employment_duration": "2 yrs"}],
 "education": ["Saint Mary's University",
  "Guru Gobind Singh Indraprastha University",
  "Hansraj model school"]}
 
 POST linkedin/_doc
 {"userprofile": {"name": "Coco Zhou",
  "current_title": "Data Analyst at DBRS",
  "location": "Canada",
  "description": "Complete both SAS Base Programming for SAS 9 and SAS Advanced•       A positive attitude, hard-working, self-motivated and detail-oriented individual with strong enthusiasmfor data analysis...see more...see more",
  "url": "https://www.linkedin.com/in/coco-zhou-421a50164/"},
 "experience": [{"company": "DBRS",
   "title": "Data Analyst",
   "dates_employed": "Feb 2019 – Present",
   "employment_duration": "1 yr 3 mos"},
  {"company": "JNC Study Abroad Platform",
   "title": "Analyst",
   "dates_employed": "Sep 2017 – Feb 2019",
   "employment_duration": "1 yr 6 mos"},
  {"company": "Bank of China",
   "title": "Summer Analyst",
   "dates_employed": "Jul 2016 – Sep 2016",
   "employment_duration": "3 mos"}],
 "education": ["University of Toronto"]}
 
 POST linkedin/_doc
 {"userprofile": {"name": "Diana Zhang",
  "current_title": "Business Analyst at Intel",
  "location": "Toronto, Canada Area",
  "description": "Experienced Business Analyst with a demonstrated history of working in the semiconductors industry. Skilledin Semiconductors, Operations Management, Cross-functional Team Leadership, Product Management, andCompetitive Analysis. Strong research professional with a Bachelor's degree focused in Mechanical...see more...see more",
  "url": "https://www.linkedin.com/in/diana-zhang-48847753/"},
 "experience": [{"company": "Intel",
   "title": "Business Analyst",
   "dates_employed": "Sep 2008 – Jan 2017",
   "employment_duration": "8 yrs 5 mos"},
  {"company": "Walmart global procurement",
   "title": "Replenishment analyst",
   "dates_employed": "Oct 2006 – Sep 2008",
   "employment_duration": "2 yrs"},
  {"company": "TCL Corporation",
   "title": "Planning Specialist",
   "dates_employed": "Jul 2004 – Sep 2006",
   "employment_duration": "2 yrs 3 mos"}],
 "education": ["Smith School of Business at Queen's University",
  "Tianjin University"]}